# Generated by Django 5.2.7 on 2025-12-13 20:35
#default admin user creation migration
#generates a default admin user with username 'admin' and password 'adminpassword'

from django.db import migrations
from django.contrib.auth import get_user_model
def create_defautl_admin(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'adminpassword')



class Migration(migrations.Migration):

    dependencies = [
        ('ClientList', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_defautl_admin),
    ]
